import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Login.module.css';

const Login: NextPage = () => {
    return (
        <div className={styles.limiter}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <div className={styles.wrap}>
                    <div className={styles.login}>
                        <Image src="/assets/img/undraw_netflix_q00o.png" alt="" width={400} height={300} />
                    </div>

                    <form className={styles['login-form']}>
                        <span className={styles['login-form-title']}>Member Login</span>

                        <div className={styles['wrap-input']}>
                            <input className={styles.input} type="text" name="email" placeholder="Email" />
                            <span className={styles['focus-input']}></span>
                            <span className={styles['symbol-input']}>
                                <i className="fa fa-envelope" aria-hidden="true"></i>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default Login;
